export const clients = [
    {
        id: 1,
        name: 'client1',
    },
    {
        id: 2,
        name: 'client2',
    },
    {
        id: 3,
        name: 'client3',
    },
    {
        id: 4,
        name: 'client4',
    },
    {
        id: 5,
        name: 'client5',
    },
];

export const data = {
    settings: {
        notifications: {
            email: true,
            sms: false,
            push: {
                android: false,
                ios: true,
            },
        },
        privacy: {
            location: false,
            camera: true,
            microphone: false,
        },
        security: {
            twoFactorAuth: false,
            backupCodes: true,
        },
    },
    preferences: {
        theme: {
            darkMode: false,
            highContrast: false,
        },
        language: {
            english: true,
            spanish: false,
            nested: {
                regionalDialects: {
                    catalan: true,
                    quechua: false,
                },
            },
        },
    },
    integrations: {
        slack: false,
        github: {
            issues: true,
            pullRequests: false,
        },
        jira: {
            basic: false,
            advanced: {
                workflows: true,
                automations: false,
            },
        },
    },
};

export const sampleAppts = [
    // --- August 10, 2025 ---
    {
        id: 1,
        date: '2025-08-10T09:00:00-07:00',
        name: 'Sophia Martinez',
        client: 'John Peters',
        clientEmail: 'john.peters@example.com',
        service: 'Haircut & Style',
    },
    {
        id: 2,
        date: '2025-08-10T10:00:00-07:00',
        name: 'David Nguyen',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 3,
        date: '2025-08-10T11:00:00-07:00',
        name: 'Olivia Thompson',
        client: 'Emma Stone',
        clientEmail: 'emma.stone@example.com',
        service: 'Dental Checkup',
    },
    {
        id: 4,
        date: '2025-08-10T12:00:00-07:00',
        name: 'Liam Johnson',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 5,
        date: '2025-08-10T13:00:00-07:00',
        name: 'Isabella Lopez',
        client: 'Ethan Miles',
        clientEmail: 'ethan.miles@example.com',
        service: 'Therapeutic Massage',
    },
    {
        id: 6,
        date: '2025-08-10T14:00:00-07:00',
        name: 'Noah Ramirez',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 7,
        date: '2025-08-10T15:00:00-07:00',
        name: 'Mia Chen',
        client: 'Lucas Price',
        clientEmail: 'lucas.price@example.com',
        service: 'Skin Care Facial',
    },
    {
        id: 8,
        date: '2025-08-10T16:00:00-07:00',
        name: 'Ethan Brooks',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 9,
        date: '2025-08-10T17:00:00-07:00',
        name: 'Ava Davis',
        client: 'Michael Rios',
        clientEmail: 'michael.rios@example.com',
        service: 'Full Body Massage',
    },
    {
        id: 10,
        date: '2025-08-10T18:00:00-07:00',
        name: 'Jackson Carter',
        client: '',
        clientEmail: '',
        service: '',
    },

    // --- August 11, 2025 ---
    {
        id: 11,
        date: '2025-08-11T09:00:00-07:00',
        name: 'Lily Nguyen',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 12,
        date: '2025-08-11T10:00:00-07:00',
        name: 'Benjamin Scott',
        client: 'Olivia Grant',
        clientEmail: 'olivia.grant@example.com',
        service: 'Teeth Whitening',
    },
    {
        id: 13,
        date: '2025-08-11T11:00:00-07:00',
        name: 'Charlotte Reed',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 14,
        date: '2025-08-11T12:00:00-07:00',
        name: 'Henry Adams',
        client: 'Aiden Torres',
        clientEmail: 'aiden.torres@example.com',
        service: 'Therapeutic Massage',
    },
    {
        id: 15,
        date: '2025-08-11T13:00:00-07:00',
        name: 'Amelia Foster',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 16,
        date: '2025-08-11T14:00:00-07:00',
        name: 'Mason Lewis',
        client: 'Ella Bryant',
        clientEmail: 'ella.bryant@example.com',
        service: 'Hair Coloring',
    },
    {
        id: 17,
        date: '2025-08-11T15:00:00-07:00',
        name: 'Harper White',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 18,
        date: '2025-08-11T16:00:00-07:00',
        name: 'Alexander Hill',
        client: 'Daniel Kim',
        clientEmail: 'daniel.kim@example.com',
        service: 'Chiropractic Session',
    },
    {
        id: 19,
        date: '2025-08-11T17:00:00-07:00',
        name: 'Scarlett Morgan',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 20,
        date: '2025-08-11T18:00:00-07:00',
        name: 'James Russell',
        client: 'Sophia Allen',
        clientEmail: 'sophia.allen@example.com',
        service: 'Hot Stone Massage',
    },

    // --- August 12, 2025 ---
    {
        id: 21,
        date: '2025-08-12T09:00:00-07:00',
        name: 'Evelyn Young',
        client: 'Liam Walker',
        clientEmail: 'liam.walker@example.com',
        service: 'Haircut & Style',
    },
    {
        id: 22,
        date: '2025-08-12T10:00:00-07:00',
        name: 'Jackson Reed',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 23,
        date: '2025-08-12T11:00:00-07:00',
        name: 'Victoria Collins',
        client: 'Olivia Hughes',
        clientEmail: 'olivia.hughes@example.com',
        service: 'Full Body Massage',
    },
    {
        id: 24,
        date: '2025-08-12T12:00:00-07:00',
        name: 'Christopher Kelly',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 25,
        date: '2025-08-12T13:00:00-07:00',
        name: 'Hazel Bennett',
        client: 'Isabella Price',
        clientEmail: 'isabella.price@example.com',
        service: 'Dental Checkup',
    },
    {
        id: 26,
        date: '2025-08-12T14:00:00-07:00',
        name: 'Matthew Rivera',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 27,
        date: '2025-08-12T15:00:00-07:00',
        name: 'Aria Torres',
        client: 'Lucas Perry',
        clientEmail: 'lucas.perry@example.com',
        service: 'Therapeutic Massage',
    },
    {
        id: 28,
        date: '2025-08-12T16:00:00-07:00',
        name: 'Logan Hayes',
        client: '',
        clientEmail: '',
        service: '',
    },
    {
        id: 29,
        date: '2025-08-12T17:00:00-07:00',
        name: 'Nora Ramirez',
        client: 'Henry Cruz',
        clientEmail: 'henry.cruz@example.com',
        service: 'Hair Styling',
    },
    {
        id: 30,
        date: '2025-08-12T18:00:00-07:00',
        name: 'Carter Long',
        client: '',
        clientEmail: '',
        service: '',
    },
];
